spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phishing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1107
    driver-class-name: com.mysql.cj.jdbc.Driver